version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/Berlin

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/Berlin

  - package-ecosystem: npm
    directory: /cms
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/Berlin

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/Berlin

  - package-ecosystem: docker
    directory: /cms
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/Berlin
