import type { Postcard } from "./types";

export const postcards: Postcard[] = [
  {
    id: "pc-004",
    ref: "PC-004",
    city: "Lisbon",
    country: "Portugal",
    year: "2019",
    date: "17.05.2019",
    text: "Tiles everywhere, hills everywhere. Wrote three pages in a café and threw away two.",
    desk: { x: 3, y: 6, rotate: -4, width: 260 },
    map: { x: 8, y: 76 },
    visibility: "public",
  },
  {
    id: "pc-011",
    ref: "PC-011",
    city: "Tallinn",
    country: "Estonia",
    year: "2021",
    date: "02.08.2021",
    text: "Old town, cold wind, extremely good internet. Felt oddly like a well-documented codebase.",
    desk: { x: 26, y: 2, rotate: 3, width: 240 },
    map: { x: 62, y: 20 },
    visibility: "public",
  },
  {
    id: "pc-019",
    ref: "PC-019",
    city: "Hamburg",
    country: "Germany",
    year: "2022",
    date: "11.03.2022",
    text: "Rain sideways. Harbour cranes like a diagram of something I should understand.",
    desk: { x: 52, y: 9, rotate: -2, width: 250 },
    map: { x: 43, y: 33 },
    visibility: "public",
  },
  {
    id: "pc-023",
    ref: "PC-023",
    city: "Trieste",
    country: "Italy",
    year: "2023",
    date: "04.09.2023",
    text: "Wind, coffee, a harbour that smells like metal. Bought a record I cannot play here.",
    desk: { x: 74, y: 4, rotate: 5, width: 230 },
    map: { x: 50, y: 58 },
    visibility: "public",
  },
  {
    id: "pc-028",
    ref: "PC-028",
    city: "Kraków",
    country: "Poland",
    year: "2022",
    date: "19.06.2022",
    text: "Ate too much, walked it off, slept nine hours. A perfect and completely unremarkable day.",
    desk: { x: 8, y: 42, rotate: 2, width: 250 },
    map: { x: 58, y: 38 },
    visibility: "public",
  },
  {
    id: "pc-034",
    ref: "PC-034",
    city: "Utrecht",
    country: "Netherlands",
    year: "2024",
    date: "28.04.2024",
    text: "Everyone cycles like it is nothing. I cycled like it was something.",
    desk: { x: 34, y: 48, rotate: -5, width: 245 },
    map: { x: 39, y: 30 },
    visibility: "public",
  },
  {
    id: "pc-039",
    ref: "PC-039",
    city: "Bergen",
    country: "Norway",
    year: "2024",
    date: "13.09.2024",
    text: "Seven hours of rain, then twenty minutes of light that made the seven hours reasonable.",
    desk: { x: 58, y: 52, rotate: 4, width: 235 },
    map: { x: 34, y: 8 },
    visibility: "public",
  },
  {
    id: "pc-046",
    ref: "PC-046",
    city: "Ljubljana",
    country: "Slovenia",
    year: "2025",
    date: "06.05.2025",
    text: "Small city, enormous ice cream. Read an entire book on a bench by the river.",
    desk: { x: 78, y: 44, rotate: -3, width: 240 },
    map: { x: 48, y: 48 },
    visibility: "public",
  },
];
