import type { Project, ProjectStatus } from "./types";

export const projectStatuses: (ProjectStatus | "all")[] = [
  "all",
  "Working",
  "In progress",
  "Completed",
  "Research",
  "Frozen",
  "Abandoned",
  "Idea",
];

// Accent colours per status — small and status-scoped, so it lives with the
// status vocabulary rather than in a component.
export const statusColor: Record<ProjectStatus, string> = {
  Working: "#2f7a3f",
  Completed: "#2f5a7a",
  "In progress": "#8a6a1f",
  Research: "#5a4a8a",
  Frozen: "#4a6a7a",
  Abandoned: "#8a3a2a",
  Idea: "#7a7a5a",
};

export const projects: Project[] = [
  {
    id: "ius-01",
    code: "IUS-01",
    name: "Personal self-hosted infrastructure",
    status: "Working",
    description: "Photos, notes, RSS, backups and a small monitoring stack running on two machines in a flat in Germany.",
    period: "2020 — ongoing",
    tech: "Docker · Caddy · Postgres · Restic",
    learned: "Operations is 10% setup and 90% the quiet Sunday when a disk starts failing.",
    cover: { from: "#3b4a3a", to: "#c7d4bf" },
    visibility: "public",
  },
  {
    id: "ius-02",
    code: "IUS-02",
    name: "OCR pipeline for supermarket catalogues",
    status: "Abandoned",
    description: "Scanned weekly catalogues, extracted products and prices, built a history nobody asked for.",
    period: "2021 — 2022",
    tech: "Python · Tesseract · Postgres",
    learned: "Data cleaning is the whole project. Also: an abandoned project is not a failed one if you can say what it taught you.",
    cover: { from: "#4a3f2a", to: "#d9c79a" },
    visibility: "public",
  },
  {
    id: "ius-03",
    code: "IUS-03",
    name: "Reverse SSH home tunnel",
    status: "Completed",
    description: "Reaching home services from anywhere without opening a single port on the router.",
    period: "2020",
    tech: "SSH · systemd · WireGuard",
    learned: "Reading the manual completely, once, is faster than reading it partly, five times.",
    cover: { from: "#2c3a4a", to: "#a9c0d1" },
    visibility: "public",
  },
  {
    id: "ius-04",
    code: "IUS-04",
    name: "Fiction writing project",
    status: "In progress",
    description: "A novel about a maintenance engineer on a structure nobody remembers building. 41 000 words.",
    period: "2023 — ongoing",
    tech: "Plain text · git · stubbornness",
    learned: "A first draft has the same purpose as a spike: prove the thing can exist.",
    cover: { from: "#4a2f3a", to: "#d5b0bd" },
    visibility: "public",
  },
  {
    id: "ius-05",
    code: "IUS-05",
    name: "Internship mentorship programme",
    status: "Working",
    description: "Structure, curriculum and review rituals for interns joining a backend team. Nine people through it.",
    period: "2022 — ongoing",
    tech: "People · docs · patience",
    learned: "The best teaching artefact is a written decision, not a meeting.",
    cover: { from: "#3a442c", to: "#c3cfa4" },
    visibility: "public",
  },
  {
    id: "ius-06",
    code: "IUS-06",
    name: "Performance engineering experiments",
    status: "Research",
    description: "A lab for JVM allocation profiling: same workload, twelve configurations, honest measurements.",
    period: "2024 — ongoing",
    tech: "Kotlin · JMH · async-profiler",
    learned: "Almost every intuition about performance is wrong until it is measured, including mine.",
    cover: { from: "#2a2a30", to: "#9aa0b5" },
    visibility: "public",
  },
  {
    id: "ius-07",
    code: "IUS-07",
    name: "Postcard scanner",
    status: "Frozen",
    description: "A tool to digitise both sides of a postcard and keep the handwriting readable. Scanned four cards.",
    period: "2023",
    tech: "SANE · ImageMagick",
    learned: "Some things are more pleasant analogue. The box is fine where it is.",
    cover: { from: "#4a4438", to: "#ddd0b4" },
    visibility: "public",
  },
  {
    id: "ius-08",
    code: "IUS-08",
    name: "Ride log",
    status: "Completed",
    description: "Self-hosted cycling tracker built before I admitted the existing app was better.",
    period: "2021",
    tech: "Kotlin · Spring · Leaflet",
    learned: "Building your own version of a solved problem is a legitimate way to learn it.",
    cover: { from: "#3d4a45", to: "#b6cbc3" },
    visibility: "public",
  },
  {
    id: "ius-09",
    code: "IUS-09",
    name: "Kitchen inventory with a barcode scanner",
    status: "Idea",
    description: "It would work. It would also mean scanning every jar of lentils I own.",
    period: "Someday",
    tech: "TBD",
    learned: "Not yet.",
    cover: { from: "#4a4a2c", to: "#d6d4a0" },
    visibility: "public",
  },
];
