// One-off generator: reads the frontend mock modules and emits the Strapi seed
// file (cms/src/seed/data.ts), so the CMS's initial content always matches the
// mock fallback exactly. Re-run with:  npx tsx scripts/gen-seed.ts
import fs from "node:fs";
import path from "node:path";
import { records } from "../src/data/vinyl";
import { postcards } from "../src/data/postcards";
import { articles } from "../src/data/articles";
import { journey } from "../src/data/journey";
import { projects } from "../src/data/projects";
import { memories } from "../src/data/memories";
import { hobbies, nowEntries, photos } from "../src/data/hobbies";
import { cvProfile, cvSections } from "../src/data/cv";
import { homeHero, homeLatest, homeCurrent, chaosCards } from "../src/data/home";

const seeds = {
  recordSeed: records.map((r) => ({
    catalog: r.catalog, artist: r.artist, title: r.title, releaseYear: r.releaseYear,
    edition: r.edition, boughtWhere: r.boughtWhere, favTrack: r.favTrack, note: r.note,
    coverFrom: r.cover.from, coverTo: r.cover.to, visibility: r.visibility,
  })),
  postcardSeed: postcards.map((p) => ({
    ref: p.ref, city: p.city, country: p.country, year: p.year, date: p.date, text: p.text,
    deskX: p.desk.x, deskY: p.desk.y, deskRotate: p.desk.rotate, deskWidth: p.desk.width,
    mapX: p.map.x, mapY: p.map.y, visibility: p.visibility,
  })),
  articleSeed: articles.map((a) => ({
    kind: a.kind, title: a.title, date: a.date, readTime: a.readTime, tags: a.tags,
    excerpt: a.excerpt, visibility: a.visibility,
  })),
  journeySeed: journey.map((e) => ({
    year: e.year, category: e.category, size: e.size, title: e.title, body: e.body,
    note: e.note ?? null, visibility: e.visibility,
  })),
  projectSeed: projects.map((p) => ({
    code: p.code, name: p.name, status: p.status, description: p.description, period: p.period,
    tech: p.tech, learned: p.learned, coverFrom: p.cover.from, coverTo: p.cover.to,
    visibility: p.visibility,
  })),
  memorySeed: memories.map((m) => ({
    kind: m.kind, title: m.title, body: m.body, filedUnder: m.filedUnder, visibility: m.visibility,
  })),
  hobbySeed: hobbies.map((h) => ({
    name: h.name, tag: h.tag, body: h.body, href: h.href, visibility: h.visibility,
  })),
  photoSeed: photos.map((p) => ({
    caption: p.caption, meta: p.meta, seed: p.seed, visibility: p.visibility,
  })),
  nowSeed: nowEntries.map((n, i) => ({
    label: n.label, text: n.text, order: i, visibility: "public",
  })),
};

const cvSeed = {
  name: cvProfile.name, role: cvProfile.role, summary: cvProfile.summary,
  location: cvProfile.location, email: cvProfile.email,
  sections: cvSections.map((s) => ({
    title: s.title,
    rows: s.rows.map((r) => ({ head: r.head, meta: r.meta, body: r.body })),
  })),
};

const homeSeed = {
  heroTitle: homeHero.title, heroBody: homeHero.body, heroYear: homeHero.year,
  latestKind: homeLatest.kind, latestTitle: homeLatest.title, latestExcerpt: homeLatest.excerpt,
  latestDate: homeLatest.date, latestReadTime: homeLatest.readTime,
  currentName: homeCurrent.name, currentLine1: homeCurrent.line1, currentLine2: homeCurrent.line2,
  chaosCards: chaosCards.map((c) => ({ tag: c.tag, text: c.text, href: c.href, tone: c.tone })),
};

const banner =
  "// GENERATED by scripts/gen-seed.ts — do not edit by hand.\n" +
  "// Initial content the CMS is seeded with on first boot; mirrors the frontend\n" +
  "// mock data so Strapi and the fallback never drift.\n\n";

let out = banner;
for (const [name, value] of Object.entries(seeds)) {
  out += `export const ${name} = ${JSON.stringify(value, null, 2)};\n\n`;
}
out += `export const cvSeed = ${JSON.stringify(cvSeed, null, 2)};\n\n`;
out += `export const homeSeed = ${JSON.stringify(homeSeed, null, 2)};\n`;

const target = path.join(__dirname, "..", "cms", "src", "seed", "data.ts");
fs.writeFileSync(target, out);
console.log(`wrote ${target} (${out.length} bytes)`);
