// GENERATED by scripts/gen-seed.ts — do not edit by hand.
// Initial content the CMS is seeded with on first boot; mirrors the frontend
// mock data so Strapi and the fallback never drift.

export const recordSeed = [
  {
    "catalog": "LS-001",
    "artist": "Talk Talk",
    "title": "Laughing Stock",
    "releaseYear": 1991,
    "edition": "EU reissue, 2016",
    "boughtWhere": "Berlin, March 2019",
    "favTrack": "After the Flood",
    "note": "Bought on a day I had nothing planned, which almost never happens. Side two is the reason I started paying attention to silence in music — and, eventually, to silence in meetings.",
    "coverFrom": "#2b3a4a",
    "coverTo": "#8fa6b8",
    "visibility": "public"
  },
  {
    "catalog": "LS-014",
    "artist": "Portishead",
    "title": "Dummy",
    "releaseYear": 1994,
    "edition": "Original press",
    "boughtWhere": "Flea market, 2020",
    "favTrack": "Roads",
    "note": "Sleeve has a coffee ring that was already there. I decided it belonged to a previous owner with better stories than mine.",
    "coverFrom": "#1e1c22",
    "coverTo": "#6b5f70",
    "visibility": "public"
  },
  {
    "catalog": "LS-027",
    "artist": "Miles Davis",
    "title": "In a Silent Way",
    "releaseYear": 1969,
    "edition": "Mono repress",
    "boughtWhere": "Hamburg, 2021",
    "favTrack": "Shhh / Peaceful",
    "note": "The record I put on when a deploy is running and I have decided not to watch the logs.",
    "coverFrom": "#4a3b2a",
    "coverTo": "#c9a26a",
    "visibility": "public"
  },
  {
    "catalog": "LS-031",
    "artist": "Boards of Canada",
    "title": "Music Has the Right to Children",
    "releaseYear": 1998,
    "edition": "2013 reissue",
    "boughtWhere": "Online, regretted the shipping",
    "favTrack": "Roygbiv",
    "note": "Sounds like a childhood I did not have, in a country I have not been to. Excellent for writing.",
    "coverFrom": "#3f5240",
    "coverTo": "#a8bf8f",
    "visibility": "public"
  },
  {
    "catalog": "LS-042",
    "artist": "Nina Simone",
    "title": "Pastel Blues",
    "releaseYear": 1965,
    "edition": "German press",
    "boughtWhere": "Trieste, 2023",
    "favTrack": "Sinnerman",
    "note": "Carried it in hand luggage across two borders. Worth it.",
    "coverFrom": "#5a2230",
    "coverTo": "#d09a86",
    "visibility": "public"
  },
  {
    "catalog": "LS-055",
    "artist": "Kraftwerk",
    "title": "Trans-Europe Express",
    "releaseYear": 1977,
    "edition": "EMI, 1977",
    "boughtWhere": "Cologne, 2022",
    "favTrack": "Franz Schubert",
    "note": "A German record bought in Germany by someone still practising his articles. Der, die, das — Trans-Europa Express.",
    "coverFrom": "#2a2a2e",
    "coverTo": "#c53a2a",
    "visibility": "public"
  },
  {
    "catalog": "LS-061",
    "artist": "Godspeed You! Black Emperor",
    "title": "Lift Your Skinny Fists Like Antennas to Heaven",
    "releaseYear": 2000,
    "edition": "Double LP",
    "boughtWhere": "Gift, 2018",
    "favTrack": "Storm",
    "note": "Given to me the winter I moved. Four sides is exactly one evening of unpacking boxes.",
    "coverFrom": "#33302b",
    "coverTo": "#8a8272",
    "visibility": "public"
  },
  {
    "catalog": "LS-078",
    "artist": "Fela Kuti",
    "title": "Zombie",
    "releaseYear": 1976,
    "edition": "Knitting Factory reissue",
    "boughtWhere": "Utrecht, 2024",
    "favTrack": "Zombie",
    "note": "Twelve minutes per side and not one of them wasted. I have tried to write software like this.",
    "coverFrom": "#2f4a2a",
    "coverTo": "#e0b23c",
    "visibility": "public"
  },
  {
    "catalog": "LS-090",
    "artist": "Steve Reich",
    "title": "Music for 18 Musicians",
    "releaseYear": 1978,
    "edition": "ECM",
    "boughtWhere": "Kraków, 2022",
    "favTrack": "Pulses",
    "note": "The best on-call soundtrack ever recorded. Nothing bad has ever happened during Section IV.",
    "coverFrom": "#e6e0d3",
    "coverTo": "#7d8fa0",
    "visibility": "public"
  },
  {
    "catalog": "LS-103",
    "artist": "Massive Attack",
    "title": "Mezzanine",
    "releaseYear": 1998,
    "edition": "2018 half-speed",
    "boughtWhere": "Birthday, 2023",
    "favTrack": "Angel",
    "note": "Loud, and the only record my downstairs neighbour has ever complimented.",
    "coverFrom": "#191b20",
    "coverTo": "#4f6b7a",
    "visibility": "public"
  },
  {
    "catalog": "LS-118",
    "artist": "Aphex Twin",
    "title": "Selected Ambient Works 85–92",
    "releaseYear": 1992,
    "edition": "Apollo repress",
    "boughtWhere": "Lisbon basement, 2019",
    "favTrack": "Xtal",
    "note": "The sleeve smells like that basement. I will not clean it.",
    "coverFrom": "#20242a",
    "coverTo": "#5fa0a8",
    "visibility": "public"
  },
  {
    "catalog": "LS-126",
    "artist": "Radiohead",
    "title": "Kid A",
    "releaseYear": 2000,
    "edition": "XL reissue",
    "boughtWhere": "Ljubljana, 2025",
    "favTrack": "How to Disappear Completely",
    "note": "I have owned this album in four formats. This is the last one, probably.",
    "coverFrom": "#7a2a1e",
    "coverTo": "#e8663f",
    "visibility": "public"
  }
];

export const postcardSeed = [
  {
    "ref": "PC-004",
    "city": "Lisbon",
    "country": "Portugal",
    "year": "2019",
    "date": "17.05.2019",
    "text": "Tiles everywhere, hills everywhere. Wrote three pages in a café and threw away two.",
    "deskX": 3,
    "deskY": 6,
    "deskRotate": -4,
    "deskWidth": 260,
    "mapX": 8,
    "mapY": 76,
    "visibility": "public"
  },
  {
    "ref": "PC-011",
    "city": "Tallinn",
    "country": "Estonia",
    "year": "2021",
    "date": "02.08.2021",
    "text": "Old town, cold wind, extremely good internet. Felt oddly like a well-documented codebase.",
    "deskX": 26,
    "deskY": 2,
    "deskRotate": 3,
    "deskWidth": 240,
    "mapX": 62,
    "mapY": 20,
    "visibility": "public"
  },
  {
    "ref": "PC-019",
    "city": "Hamburg",
    "country": "Germany",
    "year": "2022",
    "date": "11.03.2022",
    "text": "Rain sideways. Harbour cranes like a diagram of something I should understand.",
    "deskX": 52,
    "deskY": 9,
    "deskRotate": -2,
    "deskWidth": 250,
    "mapX": 43,
    "mapY": 33,
    "visibility": "public"
  },
  {
    "ref": "PC-023",
    "city": "Trieste",
    "country": "Italy",
    "year": "2023",
    "date": "04.09.2023",
    "text": "Wind, coffee, a harbour that smells like metal. Bought a record I cannot play here.",
    "deskX": 74,
    "deskY": 4,
    "deskRotate": 5,
    "deskWidth": 230,
    "mapX": 50,
    "mapY": 58,
    "visibility": "public"
  },
  {
    "ref": "PC-028",
    "city": "Kraków",
    "country": "Poland",
    "year": "2022",
    "date": "19.06.2022",
    "text": "Ate too much, walked it off, slept nine hours. A perfect and completely unremarkable day.",
    "deskX": 8,
    "deskY": 42,
    "deskRotate": 2,
    "deskWidth": 250,
    "mapX": 58,
    "mapY": 38,
    "visibility": "public"
  },
  {
    "ref": "PC-034",
    "city": "Utrecht",
    "country": "Netherlands",
    "year": "2024",
    "date": "28.04.2024",
    "text": "Everyone cycles like it is nothing. I cycled like it was something.",
    "deskX": 34,
    "deskY": 48,
    "deskRotate": -5,
    "deskWidth": 245,
    "mapX": 39,
    "mapY": 30,
    "visibility": "public"
  },
  {
    "ref": "PC-039",
    "city": "Bergen",
    "country": "Norway",
    "year": "2024",
    "date": "13.09.2024",
    "text": "Seven hours of rain, then twenty minutes of light that made the seven hours reasonable.",
    "deskX": 58,
    "deskY": 52,
    "deskRotate": 4,
    "deskWidth": 235,
    "mapX": 34,
    "mapY": 8,
    "visibility": "public"
  },
  {
    "ref": "PC-046",
    "city": "Ljubljana",
    "country": "Slovenia",
    "year": "2025",
    "date": "06.05.2025",
    "text": "Small city, enormous ice cream. Read an entire book on a bench by the river.",
    "deskX": 78,
    "deskY": 44,
    "deskRotate": -3,
    "deskWidth": 240,
    "mapX": 48,
    "mapY": 48,
    "visibility": "public"
  }
];

export const articleSeed = [
  {
    "kind": "essay",
    "title": "The migration that taught me to write",
    "date": "June 2026",
    "readTime": "12 min",
    "tags": "management, writing",
    "excerpt": "Three quarters of moving one service. The code was the easy part; the document explaining why was rewritten eleven times, and that document is what actually moved the system.",
    "visibility": "public"
  },
  {
    "kind": "technical",
    "title": "Kotlin coroutines on a boring Thursday",
    "date": "May 2026",
    "readTime": "9 min",
    "tags": "kotlin, jvm",
    "excerpt": "A structured-concurrency bug that only appeared under load, and the four wrong theories I had before the right one.",
    "visibility": "public"
  },
  {
    "kind": "note",
    "title": "Standing meetings should be shorter than the coffee",
    "date": "April 2026",
    "readTime": "2 min",
    "tags": "management",
    "excerpt": "A rule I keep breaking and keep reintroducing.",
    "visibility": "public"
  },
  {
    "kind": "project log",
    "title": "OCR pipeline, week 6: it works, sort of",
    "date": "March 2026",
    "readTime": "7 min",
    "tags": "python, side projects",
    "excerpt": "Tesseract, a scanner, 400 catalogue pages and the slow realisation that the interesting problem was never the recognition.",
    "visibility": "public"
  },
  {
    "kind": "personal",
    "title": "Learning an instrument at an age when you have opinions",
    "date": "February 2026",
    "readTime": "6 min",
    "tags": "drums",
    "excerpt": "Being bad at something in public is a skill you lose and have to deliberately regain.",
    "visibility": "public"
  },
  {
    "kind": "long read",
    "title": "On being the person who reviews instead of writes",
    "date": "January 2026",
    "readTime": "15 min",
    "tags": "management, mentorship",
    "excerpt": "What happens to your identity when the thing you were good at is no longer the thing you do all day, and why nobody warns you.",
    "visibility": "public"
  },
  {
    "kind": "technical",
    "title": "Postgres, one index and a 40× afternoon",
    "date": "Nov 2025",
    "readTime": "8 min",
    "tags": "postgres, performance",
    "excerpt": "The query plan was fine. The assumption underneath it was not.",
    "visibility": "public"
  },
  {
    "kind": "note",
    "title": "Self-hosting is a hobby, not a saving",
    "date": "Oct 2025",
    "readTime": "3 min",
    "tags": "self-hosting",
    "excerpt": "I calculated the hourly rate once. I will not do that again.",
    "visibility": "public"
  },
  {
    "kind": "personal",
    "title": "Six years of paperwork in a second language",
    "date": "Sep 2025",
    "readTime": "10 min",
    "tags": "germany, life",
    "excerpt": "Anmeldung, Steuer-ID, and the specific loneliness of understanding every word of a letter and none of its meaning.",
    "visibility": "public"
  },
  {
    "kind": "essay",
    "title": "A collection is an argument with forgetting",
    "date": "Aug 2025",
    "readTime": "11 min",
    "tags": "collecting, vinyl",
    "excerpt": "Why I keep postcards addressed to nobody and records I rarely play.",
    "visibility": "public"
  }
];

export const journeySeed = [
  {
    "year": "2014",
    "category": "work",
    "size": "m",
    "title": "First backend job",
    "body": "Java 7, a monolith and a very patient colleague who reviewed everything twice.",
    "note": null,
    "visibility": "public"
  },
  {
    "year": "2016",
    "category": "projects",
    "size": "s",
    "title": "First home server",
    "body": "An old laptop under the desk. It ran for eleven days.",
    "note": "still have the sticker",
    "visibility": "public"
  },
  {
    "year": "2017",
    "category": "work",
    "size": "s",
    "title": "Switched to Kotlin",
    "body": "Never went back.",
    "note": null,
    "visibility": "public"
  },
  {
    "year": "2018",
    "category": "life",
    "size": "l",
    "title": "Moved to Germany",
    "body": "Two suitcases, a job offer and a vocabulary of about forty words. The first month was mostly forms. The second month was mostly quiet. By the third I had a favourite bakery, which is how you know it worked.",
    "note": "the hardest good decision",
    "visibility": "public"
  },
  {
    "year": "2019",
    "category": "small",
    "size": "s",
    "title": "First 100 km ride",
    "body": "Nine hours, three wrong turns, one bakery.",
    "note": null,
    "visibility": "public"
  },
  {
    "year": "2019",
    "category": "life",
    "size": "m",
    "title": "A2 German",
    "body": "Passed with a mark that nobody has ever asked about, and which I think about often.",
    "note": null,
    "visibility": "public"
  },
  {
    "year": "2020",
    "category": "life",
    "size": "m",
    "title": "The long flat year",
    "body": "Nothing to show for it externally. Internally: learned how to be alone without it meaning something is wrong.",
    "note": "this counts too",
    "visibility": "public"
  },
  {
    "year": "2020",
    "category": "projects",
    "size": "s",
    "title": "Reverse SSH tunnel",
    "body": "So the flat could talk to the internet on my terms.",
    "note": null,
    "visibility": "public"
  },
  {
    "year": "2021",
    "category": "work",
    "size": "l",
    "title": "Tech lead",
    "body": "Given a team of four and the strange discovery that my best code was now other people’s code. Spent a year learning to say “what do you think?” before saying what I thought.",
    "note": null,
    "visibility": "public"
  },
  {
    "year": "2021",
    "category": "projects",
    "size": "m",
    "title": "OCR pipeline for supermarket catalogues",
    "body": "A weekend idea that ran for four months and produced a spreadsheet of pasta prices nobody needed.",
    "note": null,
    "visibility": "public"
  },
  {
    "year": "2022",
    "category": "small",
    "size": "s",
    "title": "Fixed the washing machine",
    "body": "One YouTube video, one hex key, enormous satisfaction.",
    "note": null,
    "visibility": "public"
  },
  {
    "year": "2022",
    "category": "work",
    "size": "m",
    "title": "Started mentoring interns",
    "body": "Nine so far. Six still write. Two are now better engineers than me at their thing.",
    "note": null,
    "visibility": "public"
  },
  {
    "year": "2023",
    "category": "life",
    "size": "m",
    "title": "B2 German",
    "body": "Can now argue with an insurance company in the second language. A real milestone.",
    "note": "ich hätte gerne…",
    "visibility": "public"
  },
  {
    "year": "2023",
    "category": "work",
    "size": "l",
    "title": "Engineering manager",
    "body": "Six people, two teams, one migration that took three quarters and taught me more about writing than any essay.",
    "note": null,
    "visibility": "public"
  },
  {
    "year": "2023",
    "category": "life",
    "size": "s",
    "title": "Started writing fiction",
    "body": "Badly, and on purpose.",
    "note": null,
    "visibility": "public"
  },
  {
    "year": "2024",
    "category": "small",
    "size": "m",
    "title": "200 km in one day",
    "body": "Elbe to the coast. Cried a little around km 170, which I am told is normal.",
    "note": null,
    "visibility": "public"
  },
  {
    "year": "2024",
    "category": "projects",
    "size": "s",
    "title": "Self-hosted everything",
    "body": "Photos, notes, RSS, backups. Two disks, one UPS.",
    "note": null,
    "visibility": "public"
  },
  {
    "year": "2025",
    "category": "life",
    "size": "m",
    "title": "Bought a drum kit",
    "body": "Month 7. Still counting out loud. The neighbours have been generous.",
    "note": "paradiddle, eventually",
    "visibility": "public"
  },
  {
    "year": "2025",
    "category": "work",
    "size": "s",
    "title": "First person I hired left for something better",
    "body": "Which is, annoyingly, the goal.",
    "note": null,
    "visibility": "public"
  },
  {
    "year": "2026",
    "category": "projects",
    "size": "m",
    "title": "This archive",
    "body": "Started because I could not remember 2020 and it turned out I had simply never written it down.",
    "note": null,
    "visibility": "public"
  }
];

export const projectSeed = [
  {
    "code": "IUS-01",
    "name": "Personal self-hosted infrastructure",
    "status": "Working",
    "description": "Photos, notes, RSS, backups and a small monitoring stack running on two machines in a flat in Germany.",
    "period": "2020 — ongoing",
    "tech": "Docker · Caddy · Postgres · Restic",
    "learned": "Operations is 10% setup and 90% the quiet Sunday when a disk starts failing.",
    "coverFrom": "#3b4a3a",
    "coverTo": "#c7d4bf",
    "visibility": "public"
  },
  {
    "code": "IUS-02",
    "name": "OCR pipeline for supermarket catalogues",
    "status": "Abandoned",
    "description": "Scanned weekly catalogues, extracted products and prices, built a history nobody asked for.",
    "period": "2021 — 2022",
    "tech": "Python · Tesseract · Postgres",
    "learned": "Data cleaning is the whole project. Also: an abandoned project is not a failed one if you can say what it taught you.",
    "coverFrom": "#4a3f2a",
    "coverTo": "#d9c79a",
    "visibility": "public"
  },
  {
    "code": "IUS-03",
    "name": "Reverse SSH home tunnel",
    "status": "Completed",
    "description": "Reaching home services from anywhere without opening a single port on the router.",
    "period": "2020",
    "tech": "SSH · systemd · WireGuard",
    "learned": "Reading the manual completely, once, is faster than reading it partly, five times.",
    "coverFrom": "#2c3a4a",
    "coverTo": "#a9c0d1",
    "visibility": "public"
  },
  {
    "code": "IUS-04",
    "name": "Fiction writing project",
    "status": "In progress",
    "description": "A novel about a maintenance engineer on a structure nobody remembers building. 41 000 words.",
    "period": "2023 — ongoing",
    "tech": "Plain text · git · stubbornness",
    "learned": "A first draft has the same purpose as a spike: prove the thing can exist.",
    "coverFrom": "#4a2f3a",
    "coverTo": "#d5b0bd",
    "visibility": "public"
  },
  {
    "code": "IUS-05",
    "name": "Internship mentorship programme",
    "status": "Working",
    "description": "Structure, curriculum and review rituals for interns joining a backend team. Nine people through it.",
    "period": "2022 — ongoing",
    "tech": "People · docs · patience",
    "learned": "The best teaching artefact is a written decision, not a meeting.",
    "coverFrom": "#3a442c",
    "coverTo": "#c3cfa4",
    "visibility": "public"
  },
  {
    "code": "IUS-06",
    "name": "Performance engineering experiments",
    "status": "Research",
    "description": "A lab for JVM allocation profiling: same workload, twelve configurations, honest measurements.",
    "period": "2024 — ongoing",
    "tech": "Kotlin · JMH · async-profiler",
    "learned": "Almost every intuition about performance is wrong until it is measured, including mine.",
    "coverFrom": "#2a2a30",
    "coverTo": "#9aa0b5",
    "visibility": "public"
  },
  {
    "code": "IUS-07",
    "name": "Postcard scanner",
    "status": "Frozen",
    "description": "A tool to digitise both sides of a postcard and keep the handwriting readable. Scanned four cards.",
    "period": "2023",
    "tech": "SANE · ImageMagick",
    "learned": "Some things are more pleasant analogue. The box is fine where it is.",
    "coverFrom": "#4a4438",
    "coverTo": "#ddd0b4",
    "visibility": "public"
  },
  {
    "code": "IUS-08",
    "name": "Ride log",
    "status": "Completed",
    "description": "Self-hosted cycling tracker built before I admitted the existing app was better.",
    "period": "2021",
    "tech": "Kotlin · Spring · Leaflet",
    "learned": "Building your own version of a solved problem is a legitimate way to learn it.",
    "coverFrom": "#3d4a45",
    "coverTo": "#b6cbc3",
    "visibility": "public"
  },
  {
    "code": "IUS-09",
    "name": "Kitchen inventory with a barcode scanner",
    "status": "Idea",
    "description": "It would work. It would also mean scanning every jar of lentils I own.",
    "period": "Someday",
    "tech": "TBD",
    "learned": "Not yet.",
    "coverFrom": "#4a4a2c",
    "coverTo": "#d6d4a0",
    "visibility": "public"
  }
];

export const memorySeed = [
  {
    "kind": "Achievement",
    "title": "You moved to a country whose language you did not speak.",
    "body": "In 2018 you arrived with two suitcases and about forty words. You did the forms, the appointments, the phone calls you dreaded. Everything about your current life stands on that.",
    "filedUnder": "journey / 2018",
    "visibility": "public"
  },
  {
    "kind": "An old goal, already reached",
    "title": "“Lead a team one day.”",
    "body": "Written in a notebook in 2017, when it felt like something other people did. You have now done it for three years, and had the boring hard days that prove it was real work, not luck.",
    "filedUnder": "cv / experience",
    "visibility": "public"
  },
  {
    "kind": "A good moment",
    "title": "The morning by the Elbe, 6:40.",
    "body": "You had not slept much. The light was ridiculous. You stopped, ate a terrible sandwich, and were happy in a way that did not need a reason.",
    "filedUnder": "photos / 2024",
    "visibility": "public"
  },
  {
    "kind": "A finished project",
    "title": "The tunnel still runs.",
    "body": "You built it in 2020 in a week of evenings and it has needed almost nothing since. Quiet things you made are still working while you read this.",
    "filedUnder": "projects / IUS-03",
    "visibility": "public"
  },
  {
    "kind": "A small success",
    "title": "You fixed the washing machine.",
    "body": "One video, one hex key, and the specific satisfaction of a thing that was broken and then was not.",
    "filedUnder": "journey / small victories",
    "visibility": "public"
  },
  {
    "kind": "Once impossible",
    "title": "You argued with an insurance company in German. And won.",
    "body": "In 2018 you could not order bread without rehearsing it first.",
    "filedUnder": "journey / 2023",
    "visibility": "public"
  },
  {
    "kind": "An object with a history",
    "title": "LS-042 — Nina Simone, Pastel Blues.",
    "body": "Carried in hand luggage from Trieste across two borders because you did not trust the hold. You still put on side one when you need to reset.",
    "filedUnder": "collections / vinyl",
    "visibility": "public"
  },
  {
    "kind": "A message from a previous you",
    "title": "“If today is only maintenance, that is still the job.”",
    "body": "Written in 2022, on a week when nothing shipped. It was true then and it is available to you now.",
    "filedUnder": "notes / undated",
    "visibility": "public"
  }
];

export const hobbySeed = [
  {
    "name": "Writing",
    "tag": "41 000 words",
    "body": "One novel in progress, several essays, a lot of deleted first paragraphs.",
    "href": "/articles",
    "visibility": "public"
  },
  {
    "name": "Drums",
    "tag": "month 7",
    "body": "A four-piece kit, mesh heads, and a metronome I have learned to respect.",
    "href": "/now",
    "visibility": "public"
  },
  {
    "name": "Cycling",
    "tag": "11 240 km",
    "body": "Long, flat, unglamorous rides. The bakery is a load-bearing part of the plan.",
    "href": "/journey",
    "visibility": "public"
  },
  {
    "name": "Self-hosting",
    "tag": "two disks, one UPS",
    "body": "Running my own small internet, badly and happily.",
    "href": "/projects",
    "visibility": "public"
  },
  {
    "name": "Collecting",
    "tag": "214 + 46",
    "body": "Records and postcards. An argument with forgetting.",
    "href": "/collections",
    "visibility": "public"
  },
  {
    "name": "Side projects",
    "tag": "nine, some alive",
    "body": "Started for curiosity, kept for the lesson, abandoned without shame.",
    "href": "/projects",
    "visibility": "public"
  }
];

export const photoSeed = [
  {
    "caption": "The flat, first week. One chair, borrowed.",
    "meta": "Germany · Feb 2018",
    "seed": 32,
    "visibility": "public"
  },
  {
    "caption": "Record shop basement, Lisbon. Smelled exactly as expected.",
    "meta": "Portugal · May 2019",
    "seed": 61,
    "visibility": "public"
  },
  {
    "caption": "Kit assembled on the living-room rug. Instructions ignored.",
    "meta": "Home · Jan 2025",
    "seed": 12,
    "visibility": "public"
  },
  {
    "caption": "Km 170. The face of a man who has made choices.",
    "meta": "Elbe route · May 2024",
    "seed": 47,
    "visibility": "public"
  },
  {
    "caption": "Harbour cranes, sideways rain.",
    "meta": "Hamburg · Mar 2022",
    "seed": 78,
    "visibility": "public"
  },
  {
    "caption": "Twenty minutes of light after seven hours of rain.",
    "meta": "Bergen · Sep 2024",
    "seed": 24,
    "visibility": "public"
  }
];

export const nowSeed = [
  {
    "label": "Working on",
    "text": "Leading two backend teams through the second half of a platform migration. Mostly writing documents, holding one-to-ones and removing obstacles that turn out to be other documents.",
    "order": 0,
    "visibility": "public"
  },
  {
    "label": "Learning",
    "text": "Drums, month 7 — currently the paradiddle, currently losing. Also German C1 grammar, at a pace best described as geological.",
    "order": 1,
    "visibility": "public"
  },
  {
    "label": "Reading",
    "text": "A biography of an engineer I had never heard of, and a very slow novel I keep restarting on purpose.",
    "order": 2,
    "visibility": "public"
  },
  {
    "label": "Building",
    "text": "This archive, and a JVM allocation-profiling lab that exists mainly so I can stop guessing.",
    "order": 3,
    "visibility": "public"
  },
  {
    "label": "Riding",
    "text": "Rebuilding base mileage after a flat winter. Target: 3 000 km this year, currently 1 180.",
    "order": 4,
    "visibility": "public"
  },
  {
    "label": "Next",
    "text": "Recording the drums badly and keeping the take. Possibly a fanzine about records nobody bought.",
    "order": 5,
    "visibility": "public"
  }
];

export const cvSeed = {
  "name": "Oleg Aleksandrov",
  "role": "Engineering Manager · Backend Developer",
  "summary": "Engineering manager and backend developer with eleven years on JVM systems. Comfortable owning services end to end, growing engineers, and preferring a clear written decision over a long meeting.",
  "location": "Germany",
  "email": "hello@olegthelilfix.me",
  "sections": [
    {
      "title": "Experience",
      "rows": [
        {
          "head": "Engineering Manager",
          "meta": "2023 — present",
          "body": "Two backend teams, six engineers. Hiring, growth plans, architecture review, and a platform migration delivered over three quarters. Reduced on-call incidents by roughly half by making ownership explicit and boring."
        },
        {
          "head": "Tech Lead, Backend",
          "meta": "2021 — 2023",
          "body": "Led a team of four on JVM services handling order and pricing flows. Introduced structured code review, a written decision log and an internship track."
        },
        {
          "head": "Senior Backend Developer",
          "meta": "2018 — 2021",
          "body": "Kotlin/Java services on Spring Boot, PostgreSQL and Kafka. Owned a payments integration end to end, including the parts nobody wanted to own."
        },
        {
          "head": "Backend Developer",
          "meta": "2014 — 2018",
          "body": "Monolith maintenance, then extraction of the first three services. Learned the difference between a system that works and a system you can operate."
        }
      ]
    },
    {
      "title": "Selected achievements",
      "rows": [
        {
          "head": "Nine interns mentored",
          "meta": "2022 — present",
          "body": "Designed the programme, curriculum and review rituals. Six converted to full-time roles."
        },
        {
          "head": "Platform migration",
          "meta": "2024 — 2025",
          "body": "Moved core services with no customer-visible downtime; the written plan became the team’s reference document."
        },
        {
          "head": "Performance work",
          "meta": "2025",
          "body": "40× improvement on a critical query path, and a profiling practice the team still uses."
        }
      ]
    },
    {
      "title": "Technical",
      "rows": [
        {
          "head": "Kotlin · Java · Spring Boot · PostgreSQL · Kafka · Docker · Kubernetes · Grafana · JMH",
          "meta": "",
          "body": "Comfortable in JVM performance work, service extraction, observability and pragmatic testing. Not a frontend engineer, and honest about it."
        }
      ]
    },
    {
      "title": "Management",
      "rows": [
        {
          "head": "Hiring · growth plans · one-to-ones · incident culture · written decisions",
          "meta": "",
          "body": "Prefer clear documents over long meetings, and explicit ownership over heroics."
        }
      ]
    },
    {
      "title": "Languages & education",
      "rows": [
        {
          "head": "Russian (native) · English (fluent) · German (B2)",
          "meta": "",
          "body": "German exam passed 2023; still working towards C1 with the enthusiasm of someone who must call the tax office."
        },
        {
          "head": "BSc, Computer Science",
          "meta": "graduated 2014",
          "body": "Thesis on distributed task scheduling; the code has mercifully been lost."
        }
      ]
    },
    {
      "title": "Contact",
      "rows": [
        {
          "head": "hello@olegthelilfix.me",
          "meta": "",
          "body": "Open to conversations about engineering management, mentorship and JVM performance. Not looking, but always reading."
        }
      ]
    }
  ]
};

export const homeSeed = {
  "heroTitle": "Grew from backend developer to engineering manager",
  "heroBody": "Eleven years, four titles, one very long migration and nine interns who now know things I do not.",
  "heroYear": "2014 → 2026",
  "latestKind": "Essay",
  "latestTitle": "The migration that taught me to write",
  "latestExcerpt": "Three quarters of moving one service. The code was the easy part; the document explaining why was rewritten eleven times.",
  "latestDate": "June 2026",
  "latestReadTime": "12 min",
  "currentName": "IUS-01 · personal infrastructure",
  "currentLine1": "uptime 214d · 2 disks · 1 UPS · 0 subscriptions",
  "currentLine2": "last change: moved backups to a second location",
  "chaosCards": [
    {
      "tag": "CV § languages",
      "text": "Russian, English, German (B2, aggressively practised)",
      "href": "/cv",
      "tone": "paper"
    },
    {
      "tag": "record LS-090",
      "text": "Music for 18 Musicians — the on-call soundtrack",
      "href": "/collections/vinyl",
      "tone": "ink"
    },
    {
      "tag": "note, undated",
      "text": "Everything in this cabinet was once a Tuesday.",
      "href": "/journey",
      "tone": "yellow"
    },
    {
      "tag": "project IUS-07",
      "text": "Postcard scanner · frozen · scanned four cards",
      "href": "/projects",
      "tone": "sage"
    },
    {
      "tag": "photo 04",
      "text": "Elbe, 6:40, the good light",
      "href": "/photos",
      "tone": "sage"
    },
    {
      "tag": "small victory",
      "text": "Fixed the washing machine (2022)",
      "href": "/journey",
      "tone": "paper"
    },
    {
      "tag": "hobby",
      "text": "Drums, month 7, still counting out loud",
      "href": "/hobbies",
      "tone": "lilac"
    },
    {
      "tag": "for later",
      "text": "You have been here before →",
      "href": "/remember",
      "tone": "accent"
    }
  ]
};
